# Generated by Django 3.1 on 2020-09-07 23:39

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200907_2339'),
        ('posts', '0004_auto_20200907_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default='Write a post...', related_name='likes', to='profiles.Profile'),
        ),
    ]
