# Generated by Django 3.1 on 2020-09-07 13:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200903_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatar.png', max_length=255, verbose_name='avatars/'),
        ),
    ]
