# Generated by Django 3.1 on 2020-09-07 15:36

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200907_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.png', max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='posts'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
